#!/usr/bin/env python3
"""Launch EvoClaw E2E trials across repos as detached processes.

Reads a trial_config.yaml, resolves the final trial_name based on flags +
existing trial dirs, and spawns one detached run_e2e per repo. Exits
immediately — workers continue in their own session (no nohup needed).
Use ./scripts/monitor.sh to track progress.

Usage:
    python scripts/run_all.py --config trial_config.yaml
    python scripts/run_all.py --config trial_config.yaml --repos navidrome ripgrep
    python scripts/run_all.py --config trial_config.yaml --force
    python scripts/run_all.py --config trial_config.yaml --new
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import yaml


def discover_repos(data_root: Path, repo_filters: list[str] | None = None) -> list[Path]:
    """Find all repo directories in data_root that contain metadata.json."""
    repos = []
    for d in sorted(data_root.iterdir()):
        if not d.is_dir():
            continue
        if not (d / "metadata.json").exists():
            continue
        if repo_filters:
            # Substring match: "navidrome" matches "navidrome_navidrome_v0.57.0_v0.58.0"
            if not any(f in d.name for f in repo_filters):
                continue
        repos.append(d)
    return repos


def get_image_name(repo_name: str) -> str:
    """Derive Docker image name from repo directory name (lowercase)."""
    return f"{repo_name.lower()}/base:latest"


def generate_collect_config(
    config_dir: Path,
    trial_name: str,
    data_root: Path,
    repos: list[Path],
) -> Path:
    """Generate a collect_results config file for monitoring."""
    config_dir.mkdir(parents=True, exist_ok=True)
    config_file = config_dir / f"{trial_name}_collect.py"

    mapping_lines = [f'    "{repo.name}": {{"path": "{repo.name}"}},' for repo in repos]

    content = f'''# Auto-generated by run_all.py for trial: {trial_name}
# Usage: python -m harness.e2e.collect_results --multi-repo --config {config_file}

DATA_ROOT = "{data_root}"

WORKSPACE_MAPPING = {{
{chr(10).join(mapping_lines)}
}}

E2E_TRIAL_NAMES = ["{trial_name}"]
'''
    config_file.write_text(content)
    return config_file


def find_max_suffix(repos: list[Path], base_name: str) -> int:
    """Max _NNN suffix existing across all repos for base_name. 0 if none."""
    max_suffix = 0
    pattern = re.compile(rf"^{re.escape(base_name)}_(\d{{3}})$")
    for repo in repos:
        e2e = repo / "e2e_trial"
        if not e2e.exists():
            continue
        for d in e2e.iterdir():
            if not d.is_dir():
                continue
            m = pattern.match(d.name)
            if m:
                max_suffix = max(max_suffix, int(m.group(1)))
    return max_suffix


def resolve_trial_name(yaml_name: str, repos: list[Path], force: bool, new: bool) -> str:
    """Resolve final trial_name based on yaml suffix + flags + existing dirs.

    Matrix (yaml without _NNN suffix):
        (none flag)  → latest existing _NNN, or _001 if none  (resume default)
        --force      → latest existing _NNN, or _001 if none  (wipe & restart)
        --new        → latest existing _NNN + 1                (always fresh)

    yaml WITH _NNN suffix is used as-is regardless of flags.
    """
    if re.match(r".*_\d{3}$", yaml_name):
        return yaml_name

    max_suffix = find_max_suffix(repos, yaml_name)
    if new:
        return f"{yaml_name}_{max_suffix + 1:03d}"
    return f"{yaml_name}_{max(max_suffix, 1):03d}"


def is_trial_completed(trial_dir: Path) -> bool:
    """True if trial summary shows all milestones completed."""
    summary = trial_dir / "evaluation" / "summary.json"
    if not summary.exists():
        return False
    try:
        s = json.loads(summary.read_text())
        completed = set(s.get("resume_state", {}).get("completed_milestones", []))
        total = s.get("total_milestones", 0)
        return total > 0 and len(completed) >= total
    except Exception:
        return False


def build_cmd(
    repo: Path,
    agent: str,
    model: str,
    timeout: int,
    trial_name: str,
    reasoning_effort: str | None,
    api_router: bool,
    force: bool,
    prompt_version: str | None = None,
) -> tuple[list[str], str]:
    """Build the run_e2e command for one repo. Returns (cmd, mode_label)."""
    repo_name = repo.name
    trial_dir = repo / "e2e_trial" / trial_name
    metadata_path = trial_dir / "trial_metadata.json"

    if not force and trial_dir.exists() and metadata_path.exists():
        return (
            [sys.executable, "-m", "harness.e2e.run_e2e", "--resume-trial", str(trial_dir)],
            "resume",
        )

    cmd = [
        sys.executable, "-m", "harness.e2e.run_e2e",
        "--repo-name", repo_name,
        "--image", get_image_name(repo_name),
        "--srs-root", str(repo / "srs"),
        "--workspace-root", str(repo),
        "--agent", agent,
        "--model", model,
        "--timeout", str(timeout),
        "--trial-name", trial_name,
    ]
    if reasoning_effort:
        cmd.extend(["--reasoning-effort", reasoning_effort])
    if api_router:
        cmd.append("--api-router")
    if prompt_version:
        cmd.extend(["--prompt-version", prompt_version])
    if force:
        cmd.append("--force")
    return cmd, ("force" if force else "fresh")


def main():
    parser = argparse.ArgumentParser(
        description="Launch EvoClaw trials (detached, fire-and-forget)",
    )
    parser.add_argument("--config", type=Path, required=True, help="Path to trial_config.yaml")
    parser.add_argument("--repos", nargs="+", default=None, help="Override repo filters (substring match)")
    parser.add_argument(
        "--force", action="store_true",
        help="Wipe & restart the latest matching trial. Kills any active worker via flock + SIGTERM, "
             "removes its container, rmtrees the trial dir, and starts fresh under the same _NNN.",
    )
    parser.add_argument(
        "--new", action="store_true",
        help="Create a new trial with the next available _NNN suffix (max+1).",
    )
    args = parser.parse_args()

    if args.new and args.force:
        print("Error: --new and --force are mutually exclusive", file=sys.stderr)
        sys.exit(1)

    # Load config
    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    data_root = Path(cfg["data_root"]).expanduser().resolve()
    yaml_trial_name = cfg["trial_name"]
    agent = cfg.get("agent", "claude-code")
    model = cfg.get("model", "claude-sonnet-4-5-20250929")
    timeout = cfg.get("timeout", 18000)
    reasoning_effort = cfg.get("reasoning_effort", None)
    api_router = cfg.get("api_router", cfg.get("drop_params", False))
    prompt_version = cfg.get("prompt_version", None)
    default_haiku_model = cfg.get("default_haiku_model", None)
    repo_filters = args.repos or cfg.get("repos", None)

    # Propagate default_haiku_model to child processes via env var
    # (ClaudeCodeFramework reads UNIFIED_DEFAULT_HAIKU_MODEL)
    if default_haiku_model:
        os.environ["UNIFIED_DEFAULT_HAIKU_MODEL"] = default_haiku_model

    # Validate
    if not data_root.exists():
        print(f"Error: data_root not found: {data_root}", file=sys.stderr)
        sys.exit(1)
    if not os.environ.get("UNIFIED_API_KEY"):
        print("Warning: UNIFIED_API_KEY not set. Agents may fail to authenticate.", file=sys.stderr)

    # Discover repos
    repos = discover_repos(data_root, repo_filters)
    if not repos:
        print(f"Error: no repos found in {data_root}", file=sys.stderr)
        sys.exit(1)

    # Resolve trial name based on yaml + flags + existing trial dirs
    trial_name = resolve_trial_name(yaml_trial_name, repos, args.force, args.new)

    mode_label = (
        "--force (wipe & restart)" if args.force
        else "--new (fresh next suffix)" if args.new
        else "default (resume latest)"
    )

    print("=" * 60)
    print("  EvoClaw Run All  (fire-and-forget)")
    print("=" * 60)
    print(f"  Data root:    {data_root}")
    print(f"  Trial name:   {trial_name}")
    print(f"  Agent:        {agent}")
    print(f"  Model:        {model}")
    print(f"  Prompt:       {prompt_version}")
    print(f"  Timeout:      {timeout}s")
    print(f"  Repos:        {len(repos)}")
    print(f"  Mode:         {mode_label}")
    print("=" * 60)

    # Generate collect config for monitor.sh
    project_root = Path(__file__).resolve().parent.parent
    log_dir = project_root / ".evoclaw"
    log_dir.mkdir(parents=True, exist_ok=True)
    collect_config = generate_collect_config(
        config_dir=log_dir,
        trial_name=trial_name,
        data_root=data_root,
        repos=repos,
    )

    # Launch each repo detached
    launched = 0
    skipped = 0
    for repo in repos:
        trial_dir = repo / "e2e_trial" / trial_name
        if not args.force and is_trial_completed(trial_dir):
            print(f"\033[0;34m[SKIP]\033[0m       {repo.name:<50}  (already completed)")
            skipped += 1
            continue

        cmd, mode = build_cmd(
            repo, agent, model, timeout, trial_name,
            reasoning_effort, api_router, args.force, prompt_version,
        )
        log_path = log_dir / f"{repo.name}.log"
        ts = time.strftime("%Y-%m-%d %H:%M:%S")
        with open(log_path, "ab") as logf:
            logf.write(f"\n\n===== launched at {ts} ({mode}) =====\n".encode())
            logf.flush()
            proc = subprocess.Popen(
                cmd,
                cwd=str(project_root),
                stdout=logf,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                start_new_session=True,  # detach: survive shell exit
            )
        print(f"\033[0;32m[LAUNCHED]\033[0m  {repo.name:<50}  PID={proc.pid}  ({mode})")
        launched += 1

    print()
    print(f"  {launched} launched, {skipped} skipped")
    print()
    print(f"Monitor:       ./scripts/monitor.sh {trial_name}")
    print(f"Per-repo logs: {log_dir}/<repo>.log")
    print(f"Collect cfg:   {collect_config}")
    print()


if __name__ == "__main__":
    main()
